### ISSUE TITLE
Unable to host books with FileDescriptor on `Server`

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/libkiwix#1015]
We introduced the hosting books feature for `KiwixCustomApps` a few days back, and now we are using `FileDescriptor` to read the zim files from the asset folder in https://github.com/kiwix/kiwix-android/pull/3516. While refactoring the server functionality to use the `FileDescriptor` to host the zim file on `Server` we have seen that the server is unable to host books with `FileDescriptor`.

I don't know if it is possible to host zim files with `FileDescriptor`, if possible how much time it will take to implement. 
I am creating this ticket for this bug to further conversation on this.

**Comment by veloman-yunkan** [comment]
Support in `libzim` for opening ZIM files via a file descriptor boils down to a [hack](https://github.com/openzim/libzim/blob/9.1.0/src/file_part.h#L48-L49) that just [converts the fd into a Unix-specific file path](https://github.com/openzim/libzim/blob/9.1.0/src/fs_unix.cpp#L140-L146) that is valid within the same process and as long as the original fd stays open. openzim/libzim#860 didn't change that.

Now I am not sure that API-wise it makes sense to pretend that we support opening ZIM files via file-descriptor. Instead we better support only file-paths and let the clients convert fds to paths on their own.

However, opening ZIMs via fds is different in that it also requires supplying offset and data size values.
So currently (i.e. with openzim/libzim#860 recently merged) a ZIM-reference (the data required to open a ZIM archive) is one of the following:

1. A collection of file paths (a single file being just a special case)
2. A collection of (fd, offset, data-chunk-size) triplets

I think that we should unify those two cases into "**a collection of (file-path, offset, data-chunk-size) triplets**", introduce in `libzim` a class say (`ArchiveRef`) for that data and just extend the rest of openzim/kiwix code so that APIs that previously took an `std::string` representing the file path start accepting an `ArchiveRef` too.

@kelson42 @mgautierfr What do you think?

**Comment by kelson42** [comment]
@veloman-yunkan @mgautierfr To me this ticket is basically a duplicate of https://github.com/openzim/libzim/issues/852 and I would like to close ot at such.

**Comment by mgautierfr** [comment]
I think this issues around fd are a bit different, as they may have different root cause:
- This issue is about opening embedded (split ?) files and I think it is fixed by https://github.com/openzim/libzim/pull/860
- Issue https://github.com/openzim/libzim/issues/852 is about a permission removed in the kiwix-android application which (presumably) prevent us to reopen `/proc/<pid>/fd/<fd>` file.

However, (if this issue is not already fixed) we should tackle this thinking globally about an api to allow us to read data from source for which we don't have a path or we cannot directly reopen it. 

So no need to have several issues about that, I will close this issue in favor of openzim/libzim#852.

**Comment by MohitMaliFtechiz** [comment]
> This issue is about opening embedded (split ?) files and I think it is fixed by https://github.com/openzim/libzim/pull/860

@mgautierfr According to your comment for this issue, we are again introducing the hotspot feature for the custom app in https://github.com/kiwix/kiwix-android/pull/4223. However, we are still experiencing the same issue reported in this issue.

Now the ZIM file is correctly opening in the reader via fd chunks, but when we are trying to host the ZIM file on the server it is not showing the ZIM file there. But the language of the book is showing on the server.

![Image](https://github.com/user-attachments/assets/d785f186-68a4-4ea9-a7f7-bfc35a63f4a4)

Additionally, this fd can be read by the `/dev/fd/xxx`, here are the logs:

**Before**
```kotlin
KiwixServer             org.kiwix.kiwixcustomcustomexample   E   FD is valid = true 
FD can read via the dev/fd/fdNumber = true

```

**After**
```kotlin
org.kiwix.kiwixcustomcustomexample   E  After 5 second FD is valid = true 
 FD can read via the dev/fd/fdNumber = true
```

I am not reopening this issue as you have close this issue in favour of https://github.com/openzim/libzim/issues/852 which is the root cause of this issue. Probably this is not working due to search functionality on the server(We can search inside the ZIM file on server which usages the xapian and Xapian needs the file path). 

But if anything we can do in this do let me know.
