### ISSUE TITLE
Out-of Service Worker refresh not working with the Viewer

### ISSUE THREAD

**Issue by Popolechien** [kiwix/libkiwix#994]
So @RavanJAltaie and I are both online checking out https://library.kiwix.org/viewer#athena_fr_all_2023-05/A/athena.unige.ch/athena/ and while I do see the zim file as expected, she does not see images (see screenshots we took pretty much at the same time).

![Capture d’écran 2023-08-25 à 16 09 43](https://github.com/kiwix/kiwix-tools/assets/21675885/a76f4155-f312-4c90-a140-c61ce0647470)
![image_720](https://github.com/kiwix/kiwix-tools/assets/21675885/85988829-1033-429d-9890-39d1ccb21479)

Hard refresh did not seem to change anything and her internet connection was good. Both of us are on Google Chrome.

**Comment by RavanJAltaie** [comment]
@mgautierfr I followed your instructions and it worked fine, all content was available
Any action I should take to further report this issue and observe whenever is solved?

**Comment by kelson42** [comment]
@mgautierfr @rgaudin I don't understand the essence of the ticket. When does the problem occurs (obviously the SW works fine "in general"). Do we have a slight idea why the autoredirection to the homepage seems to fail?

**Comment by rgaudin** [comment]
@RavanJAltaie this is not a recipe issue ; as you can see this is now in the libkiwix repo. You're good 😉

@kelson42 the important thing, if you did not notice, is that @Popolechien shared a link to **some page** inside the ZIM, and not the ZIM homepage (ZIM homepage eventually redirects to it which explains why he shared it).
This page, as any other non-home HTML page includes a piece of code (see my comment above) that detects if the SW is installed and available and redirects if not (via a delayed `window.location` change).

It seems that the Viewer code, which we know observes and manipulates iframe URL changes prevents the redirection from happening leaving the _raw_ HTML content stored in the ZIM entry displayed. Without the SW, resources (hence images) are not fetched.

This might be due to the iframe jailing, the viewer JS code observing the iframe or a combination of both.

As far as I understand it, it should affect all zimit ZIMs under similar condition: arriving on a _new_ (not previously visited) ZIM via a direct URL.

**Comment by kelson42** [comment]
@rgaudin Very serious regression then!

**Comment by veloman-yunkan** [comment]
> This might be due to the iframe jailing, the viewer JS code observing the iframe or a combination of both.

@rgaudin You missed another option a hint to which was available in your previous comment:

```
<head><script>
// No SW Fallback check: hit if loaded via direct link (no SW installed or not supported)
if (window.top === window && !window._WBWombat) {
    ^^^^^^^^^^^^^^^^^^^^^
    // An attempt to initialize the service worker is made only
    // if the zimit app is running in the top window (which, under
    // the iframe based viewer, it doesn't)
```

**Comment by rgaudin** [comment]
Indeed! Thank you for noticing. I'll transfer to warc2zim. It seems we now need to support both out-of-frame and in-frame.

**Comment by rgaudin** [comment]
Closing in favor of https://github.com/openzim/warc2zim/issues/119
